/// Small non-cryptographic fingerprint, rendered as a hex signature.
///
/// Port of the website's `fingerprint()` (FNV-style double hash using
/// `Math.imul` semantics), so signatures generated here match signatures
/// generated by the web prototype for the same input.
library;

int _imul(int a, int b) => ((a & 0xFFFFFFFF) * (b & 0xFFFFFFFF)) & 0xFFFFFFFF;

String fingerprint(String text) {
  var h1 = 0x811c9dc5;
  var h2 = 0x01000193;
  for (var i = 0; i < text.length; i++) {
    final c = text.codeUnitAt(i);
    h1 = _imul(h1 ^ c, 0x01000193);
    h2 = _imul(h2 + c * (i + 7), 0x85ebca6b);
  }
  return (h1.toRadixString(16).padLeft(8, '0') +
          h2.toRadixString(16).padLeft(8, '0'))
      .toUpperCase();
}
